global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'ecommerce-services'
    metrics_path: /actuator/prometheus
    static_configs:
      - targets:
          - usuario-service:8081
          - pedido-service:8082
          - produtos-service:8083
          - pagamento-service:8085
