name: Deploy Infra Auxiliar (Kafka, Zookeeper, Kafka UI, Eureka)

on:
  push:
    branches: [ main, master ]

jobs:
  deploy:
    name: Deploy Infra na EC2
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v4

      - name: Conectar via SSH e rodar docker-compose
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ubuntu
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
           cd ~/eureka-infra
           git pull origin master
           docker compose down
           docker compose up -d --build
